version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
